wenzhixin/bootstrap-table-examples

index.html
methods/checkby-uncheckby.html

Documentation updated according to https://github.com/wenzhixin/bootstrap-table/pull/532

Methods checkBy/uncheckBy example

---

integrate/angularjs.html
integrate/app.js

Updates for wenzhixin/bootstrap-table#1129

Fix angularjs example

---

index.html
methods/updateByUniqueId.html

Requires: https://github.com/wenzhixin/bootstrap-table/pull/1592
This is the example of the new proposed method updateByUniqueId.

New Method Example: updateByUniqueId

---

extensions/sticky-header.html

Sticky header

---

README.md

Added to compliment other changes in https://github.com/wenzhixin/bootstrap-table/issues/2380 to make more obvious where to post issues to

update to help direct issues to main repo, see #2380

---

extensions/group-by-v2.html
extensions/group-by.html
index.html
index.html.conf
json/data6.json

I created a simple example of group-by.

Simple example for "Group by"

---

extensions/defer-url.html

see: [Bootstrap Table Defer URL Extension #2738](https://github.com/wenzhixin/bootstrap-table/pull/2738)

Bootstrap Table Defer URL Extension Example

---

extensions/treegrid.html
json/treegrid.json

the example for treegrid plugin

add treegrid demo

---

index.html
options/show-button-icons.html
options/show-button-text.html

Documentation for https://github.com/wenzhixin/bootstrap-table/pull/4388

Added documentation for 4324

---

index.html
options/buttons-order.html

ref https://github.com/wenzhixin/bootstrap-table/pull/4708

Added buttonsOrder option

---

column-options/search-highlight-formatter.html
index.html
options/search-highlight.html

https://github.com/wenzhixin/bootstrap-table/pull/5216

Added examples for the feature request 5215

---

index.html
options/buttons.html

https://github.com/wenzhixin/bootstrap-table/pull/5227

Added an example for a custom button

---

index.html
options/table-search-selector.html

Ref https://github.com/wenzhixin/bootstrap-table/pull/5292

Added documentation for the issue 5290 (custom search input)

---

options/footer-field.html

See: https://github.com/wenzhixin/bootstrap-table/pull/5625
Current: 
Fixed:

Fix example of Footer Field

---

index.html
options/regex-search.html

Example for:  https://github.com/wenzhixin/bootstrap-table/pull/5810

Regex search example

---

methods/filter-by.html

Added a basic custom filterBy example

---

index.html
options/sort-empty-last.html

ref https://github.com/wenzhixin/bootstrap-table/pull/6302

Added an example for the new option "sortEmptyLast"

---

server/examples.js

convert any value to string to compare

---

index.html
options/table-escape-title.html

Added example for the table option "escapeTitle"

Added example for the table option "escapeTitle"

---

index.html
options/searchable.html

https://github.com/wenzhixin/bootstrap-table/pull/6711

Added searchable.html option example

---

column-options/switchable.html

https://live.bootstrap-table.com/code/marceloverdijk/15617
Improvement as discussed here https://github.com/wenzhixin/bootstrap-table/issues/6798

Added switchableLabel column option

---

methods/sort-by.html

https://examples.bootstrap-table.com/#methods/sort-by.html

Fixed sort by not working bug

---

extensions/addrbar-page.html

https://github.com/wenzhixin/bootstrap-table/issues/6474

Added sortReset to addrbar extension

---

extensions/export.html

https://github.com/wenzhixin/bootstrap-table/issues/6938

Updated export plugin version

---

options/icons-prefix.html

https://github.com/wenzhixin/bootstrap-table/pull/7190

Added support for setting icons automatically by iconsPrefix

---

index.html
options/fixed-scroll.html

https://github.com/wenzhixin/bootstrap-table/pull/7193

Added fixedScroll option

---

extensions/print.html
options/table-locale.html

https://github.com/wenzhixin/bootstrap-table/pull/7238

Updated print and locale examples

---

index.html
options/pagination-load-more.html

https://github.com/wenzhixin/bootstrap-table/pull/7246

Added paginationLoadMore table option

---

extensions/cookie.html

https://github.com/wenzhixin/bootstrap-table/pull/7320

Added locales support

---

index.html
options/buttons-attribute-title.html

Using: https://github.com/wenzhixin/hint-css

Added buttonsAttributeTitle option

---

extensions/export.html

Tested for export with `showFooter`.

Added show footer to export extension example

---

options/search-highlight.html

https://github.com/wenzhixin/bootstrap-table/pull/7425

Updated search highlight example

---

index.html
methods/sort-reset.html

Example for: https://github.com/wenzhixin/bootstrap-table/pull/7432

Example for feature/7432

---

column-options/formatter.html

Update column options `formatter` example.
Refs https://github.com/wenzhixin/bootstrap-table/pull/7444

Update column formatter example with returning HTMLElement

---

index.html
methods/get-footer-data.html

Adds an example for implemented method `getFooterData` at [Pull 7537](https://github.com/wenzhixin/bootstrap-table/pull/7537)

Added example for getFooterData

---

webpack-starter/package.json
webpack-starter/src/index.js
webpack-starter/src/jquery.js
webpack-starter/webpack.config.js

Fixed https://github.com/wenzhixin/bootstrap-table/issues/7167

Updated webpack and bootstrap

---

options/row-style.html

Fixed https://github.com/wenzhixin/bootstrap-table/issues/7582

Fixed row style example not working bug

---

welcomes/from-data.html

Ref: https://github.com/wenzhixin/bootstrap-table/pull/7584

Added field attr example for data

---

issues/563.html

Fix https://github.com/wenzhixin/bootstrap-table/issues/7586

Updated 563 example

---

extensions/addrbar-page.html
extensions/addrbar.html
extensions/auto-refresh.html
extensions/cookie.html
extensions/copy-rows.html
extensions/custom-view.html
extensions/defer-url.html
extensions/editable.html
extensions/export.html
extensions/filter-control.html
extensions/fixed-columns.html
extensions/group-by-v2.html
extensions/i18n-enhance.html
extensions/key-events.html
extensions/mobile.html
extensions/multiple-sort.html
extensions/page-jump-to.html
extensions/pipeline.html
extensions/print.html
extensions/reorder-columns.html
extensions/reorder-rows.html
extensions/resizable.html
extensions/sticky-header.html
extensions/toolbar.html
extensions/treegrid.html

Rebuild extensions to es6 and new template

Rebuild extensions to es6 and new template
